export const SystemsSpecial = Object.freeze([
  "Terra",
  "Solaris",
  "Galatea",
  "Luthien",
  "New Avalon",
  "Sian",
  "Atreus (FWL)",
  "Rasalhague",
  "St. Ives",
  "Oberon",
  "Taurus",
  "Canopus",
  "Alpheratz",
  "Circinus",
  "Alphard (MH)",
  "Lothario",
  "Coromodir",
  "Tharkad",
  "Asturias",
  "Far Reach",
  "Albion (Clan)",
  " Zara(Homer 2850 +)",
  "Tamaron",
  "Strato Domingo",
  "Shadow",
  "Arcadia (Clan)",
  "Dagda (Clan)",
  "Kirin",
  "Hector",
  "Ironhold",
  "Barcella",
  "Strana Mechty",
  "Huntress",
  "Lum",
  "Sheridan (Clan)",
  "New Kent",
  "Tiber (Clan)",
  "New Delphi",
  "Blackbone (Nyserta 3025+)",
  "Bremen (HL)",
  "Trondheim (JF)",
  "Tortuga Prime",
  "Gotterdammerung",
  "Thala"
]);
